### PR TITLE
Stack effect feature

### PR DESCRIPTION
**Pull request by gonzaloriestra**
I added a stack effect to the cards, keeping backwards compatibility (not shown by default), and customizable with several parameters: cards count, separation, zoom, animation speed...

I also added a couple of new events: `onSwipedAborted` and `onSwiping` (not very related, maybe it should be another PR, sorry).

I couldn't try it with your examples, but here you can see an example:
https://photos.app.goo.gl/STyNQXI95fKuiQT93

### CODE REVIEW

**Comment by alexbrillant** [comment]
👍 💯 really good job wow thanks alot m8 !

**Comment by gonzaloriestra** [comment]
Thanks to you for sharing this great library :slightly_smiling_face:

**Comment by alexbrillant** [comment]
onSwipedAborted and onSwiping need a default props; it crashes otherwise

**Comment by gonzaloriestra** [comment]
@alexbrillant hey, thanks for fixing that and merging it. But I didn't update the version, shouldn't you bump it?

**Pull request merged**
