### PR TITLE
Allows override for container style

### PR DESCRIPTION
**Pull request by mcavaliere**
I've added a `containerStyle` prop that will allow overrides for the containing `<View>`.  This helps a lot, especially in cases where we have this component inside a screen with others.

### CODE REVIEW

**Comment by atennapel** [comment]
You should add it to `propTypes` as well. Would be great if this gets merged!

**Comment by mcavaliere** [comment]
@atennapel Good call - added!

**Comment by mcavaliere** [comment]
🎉 Thanks @alexbrillant!

**Comment by AnatuGreen** [comment]
I am new to this. How does one implement this? Because I have tried and it is not working.
<View containerStyle = {{backgroundColor: 'red'}} >
<View containerStyle = {backgroundColor: 'red'}} >

are not working

**Comment by AnatuGreen** [comment]
> I am new to this. How does one implement this? Because I have tried and it is not working. <View containerStyle = {{backgroundColor: 'red'}} > <View containerStyle = {backgroundColor: 'red'}} >
> 
> are not working

Please assist

**Comment by AnatuGreen** [comment]
Ok. I have solved this. Realized I had to put the ContainerStyle like this:
```
 ......
<Swiper
          ref={swiper => {
            this.swiper = swiper
          }}
          onSwiped={() => this.onSwiped('general')}
          onSwipedLeft={() => this.onSwiped('left')}
          onSwipedRight={() => this.onSwiped('right')}
          onSwipedTop={() => this.onSwiped('top')}
          onSwipedBottom={() => this.onSwiped('bottom')}
          // removed onTapCard={this.swipeLeft}
          cards={this.state.cards}
          cardIndex={this.state.cardIndex}
          showSecondCard={false}

          containerStyle ={{backgroundColor: 'red'}}

          cardVerticalMargin={80}
          renderCard={this.renderCard}
          onSwipedAll={this.onSwipedAllCards}
          stackSize={3}
          stackSeparation={15}
     
```
```

**Pull request merged**
